<header id="header" data-current-skin={{uxctrl.currentSkin}} data-ng-include="'<?php echo $this->baseurl.'/partial/header';?>'" data-ng-controller="headerCtrl as hctrl"></header>
<section id="main">
    <aside id="sidebar" data-ng-include="'<?php echo $this->baseurl.'/partial/mainmenu';?>'" data-ng-class="{ 'toggled': uxctrl.sidebarToggle.left === true }"></aside>
    <section id="content">

        <div class="container">
            <div class="block-header" style="margin-right: -12px;">
                <h2>Dashboard</h2>

                <ul class="actions">
                    <li>
                        <a href="">
                            <i class="zmdi zmdi-trending-up"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="zmdi zmdi-check-all"></i>
                        </a>
                    </li>
                    <li class="dropdown" uib-dropdown>
                        <a href="" uib-dropdown-toggle>
                            <i class="zmdi zmdi-more-vert"></i>
                        </a>

                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <a href="">Refresh</a>
                            </li>
                            <li>
                                <a href="">Manage Widgets</a>
                            </li>
                            <li>
                                <a href="">Widgets Settings</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>

            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <div class="mini-charts-item bgm-cyan">
                        <div class="clearfix">
                            <div class="chart stats-bar" data-sparkline-bar=""><canvas width="83" height="45" style="display: inline-block; width: 83px; height: 45px; vertical-align: top;"></canvas></div>
                            <div class="count">
                                <small>Items in Inventory</small>
                                <h2>987,459</h2>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 col-md-3">
                    <div class="mini-charts-item bgm-lightgreen">
                        <div class="clearfix">
                            <div class="chart stats-bar-2" data-sparkline-bar=""><canvas width="83" height="45" style="display: inline-block; width: 83px; height: 45px; vertical-align: top;"></canvas></div>
                            <div class="count">
                                <small>No. of Customers</small>
                                <h2>356,785K</h2>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 col-md-3">
                    <div class="mini-charts-item bgm-orange">
                        <div class="clearfix">
                            <div class="chart stats-line" data-sparkline-line=""><canvas width="85" height="45" style="display: inline-block; width: 85px; height: 45px; vertical-align: top;"></canvas></div>
                            <div class="count">
                                <small>Total Sales</small>
                                <h2>$ 458,778</h2>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 col-md-3">
                    <div class="mini-charts-item bgm-bluegray">
                        <div class="clearfix">
                            <div class="chart stats-line-2" data-sparkline-line=""><canvas width="85" height="45" style="display: inline-block; width: 85px; height: 45px; vertical-align: top;"></canvas></div>
                            <div class="count">
                                <small>Support Tickets</small>
                                <h2>23,856</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>


    </section>
    
</section>

<footer id="footer" data-ng-include="'<?php echo $this->baseurl.'/partial/footer';?>'"></footer>
