<ul class="header-inner clearfix">
    <li id="menu-trigger" data-target="mainmenu" data-toggle-sidebar data-model-left="uxctrl.sidebarToggle.left" onclick="wew()" data-ng-class="{ 'open': uxctrl.sidebarToggle.left === true }">
        <div class="line-wrap">
            <div class="line top"></div>
            <div class="line center"></div>
            <div class="line bottom"></div>
        </div>
    </li>
    <li class="logo">
        <a data-ui-sref="home" data-ng-click="toggleChildAccordion($event);">Student Career</a>
    </li>

    <li class="pull-right">
        <ul class="top-menu">

            <li class="dropdown" uib-dropdown>
                <a uib-dropdown-toggle href="">
                    <i class="tm-icon zmdi zmdi-more-vert"></i>
                </a>
                <ul class="dropdown-menu dm-icon pull-right">
                    <li class="skin-switch  hidden-xs">
                        <span ng-repeat="w in uxctrl.skinList | limitTo : 6" class="ss-skin bgm-{{ w }}" data-ng-click="uxctrl.skinSwitch(w)"></span>
                    </li>
                    <li class="hidden">
                        <a href="" data-ui-sref="settings.module">
                        <i class="zmdi zmdi-settings"></i> Module
                        </a>
                    <li class="divider hidden-xs"></li>
                    <li>
                        <a href="" ng-click="doLogout()"><i class="zmdi zmdi-time-restore"></i> Logout</a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
    <li class="pull-right text-right p-r-5" style="width: 150px; color: #fff; cursor: default;">
        Signed in as<br><a class="p-r-0 c-white" data-ui-sref="profile" data-ng-click="uxctrl.lvMenuStat=false" class="badge" style="cursor: default;">{{user_info.email_address}}</a>
    </li>
</ul>


<script type="text/javascript">
    function wew(){
        if($('.dim').is(":visible")==true){
            $('.dim').fadeOut(function(){
                this.remove();
            });
        }
        else{
            $('.content-page').prepend('<div class="dim"></div>');
            $('.dim').hide().fadeIn();
        }
    }
    // CLICK ON SIDEBAR LINKS
    $('#sidebar a[href!=""]').on('click', function(){
      if($('#menu-trigger .line-wrap').is(':visible')){
        $('#menu-trigger').click();
      }
    })
</script>
