<?php $session  =   $this->session->get('auth-psslai'); ?>
<div class="sidebar-inner c-overflow">
    <ul class="main-menu">
        <li><a data-ui-sref-active="" data-ui-sref="home" data-ng-click="toggleChildAccordion($event);" data-current-skin="{{ sideMenu.child == 'home' ? skin : '' }}"><i class="zmdi zmdi-home"></i> DASHBOARD</a></li>
        <li><a data-ui-sref-active="" data-ui-sref="student.list" data-ng-click="toggleChildAccordion($event);" data-current-skin="{{ sideMenu.child == 'student_list' ? skin : '' }}"><i class=""></i> STUDENT LIST</a></li>
        <li><a data-ui-sref-active="" data-ui-sref="subject.list" data-ng-click="toggleChildAccordion($event);" data-current-skin="{{ sideMenu.child == 'subject_list' ? skin : '' }}"><i class=""></i> SUBJECT LIST</a></li>
        <li><a data-ui-sref-active="" data-ui-sref="cjl.list" data-ng-click="toggleChildAccordion($event);" data-current-skin="{{ sideMenu.child == 'career_job_list' ? skin : '' }}"><i class=""></i> CAREER JOB LIST</a></li>
        <li><a data-ui-sref-active="" data-ui-sref="tracking.list" data-ng-click="toggleChildAccordion($event);" data-current-skin="{{ sideMenu.child == 'tracking' ? skin : '' }}"><i class=""></i> TRACKING</a></li>

        <!-- <li class="sub-menu" data-ng-class="{ 'active toggled': sideMenu.parent == 'student'  || sideMenu.parent == 'student_list' }" ng-click="toggleAccordion($event);">
            <a href="" toggle-submenu><i class="zmdi zmdi-accounts-alt"></i>CAREER SETUP</a>
            <ul>
                <li><a data-ui-sref-active="" data-ui-sref="career.list" data-ng-click="toggleChildAccordion($event);" data-current-skin="{{ sideMenu.child == 'opportunity' ? skin : '' }}"><i class="zmdi zmdi-case"></i> OPPORTUNITY</a></li>
            </ul>
        </li> -->


        <!-- <li class="sub-menu" data-ng-class="{ 'active toggled': uxctrl.$state.includes('users')}" ng-click="toggleAccordion($event);">
            <a href="" toggle-submenu><i class="zmdi zmdi-accounts-alt"></i>USER SETUP</a>
            <ul>
                <li><a data-ui-sref-active="" data-ui-sref="users.users" data-ng-click="toggleChildAccordion($event);" data-current-skin="{{ sideMenu.child == 'user' ? skin : '' }}"><i class="zmdi zmdi-case"></i> User</a></li>
            </ul>
        </li>
        <li class="sub-menu" data-ng-class="{ 'active toggled': sideMenu.parent == 'career'  || sideMenu.parent == 'career_setup' }" ng-click="toggleAccordion($event);">
            <a href="" toggle-submenu><i class="zmdi zmdi-accounts-alt"></i>CAREER SETUP</a>
            <ul>
                <li><a data-ui-sref-active="" data-ui-sref="career.list" data-ng-click="toggleChildAccordion($event);" data-current-skin="{{ sideMenu.child == 'opportunity' ? skin : '' }}"><i class="zmdi zmdi-case"></i> OPPORTUNITY</a></li>
            </ul>
        </li> -->

        <!-- <li class="sub-menu" data-ng-class="{ 'active toggled': uxctrl.$state.includes('user_setup') }" ng-click="toggleAccordion($event);">
            <a href="" toggle-submenu><i class="zmdi zmdi-accounts-alt"></i>SETTING</a>
            <ul>
                <li><a data-ui-sref-active="" data-ui-sref="settings.student" data-ng-click="toggleChildAccordion($event);" data-current-skin="{{ sideMenu.child == 'user' ? skin : '' }}"><i class="zmdi zmdi-case"></i> Student</a></li>
            </ul>
        </li>

        <li class="sub-menu" data-ng-class="{ 'active toggled': sideMenu.parent == 'settings' }" ng-click="toggleAccordion($event);">
            <a href="" toggle-submenu><i class="zmdi zmdi-accounts-alt"></i>CAREER</a>
            <ul>
                <li><a data-ui-sref-active="" data-ui-sref="career.list" data-ng-click="toggleChildAccordion($event);" data-current-skin="{{ sideMenu.child == 'user' ? skin : '' }}"><i class="zmdi zmdi-case"></i> List?</a></li>
            </ul>
        </li> -->
    </ul>
</div>
