
<div class="container" data-ng-controller="InventoryCtrl as cCtrl" ng-init="OnInit();getInventory();">
    <div class="block-header p-l-0" style="margin-right: -12px;">
        <h2><b>Inventory</b></h2>

        <ul class="actions">
            <li>
                <div class="form-group">
                    <div class="fg-line">
                        <input type="text" placeholder="Search" ng-change="getInventory()" ng-model="inventory_search" class="input-sm form-control seach-module" maxlength="50">
                    </div>
                </div>
            </li>
            <li title="Refresh">
                <a href="" data-ng-click="getInventory(); "><i class="zmdi zmdi-refresh" ></i></a>
            </li>
        </ul>
    </div>

    <div class="card">
        <a  title="Add New" class="btn btn-float m-btn ng-scope waves-effect waves-circle" href="" ng-click="addInventoryForm();" data-current-skin={{uxctrl.currentSkin}}><i class="zmdi zmdi-plus"></i></a>
        <div class="card-body table-responsive">
            <table ng-table="inventoryTable" class="table table-display-inline table-striped table-vmiddle">
                <thead>
                    <tr>
                        <th></th>
                        <th> ITEM NAME</th>
                        <th> BRAND </th>
                        <th> CATEGORY </th>
                        <th> PRICE </th>
                        <th> QTY </th>
                        <th> CREATED BY </th>
                    </tr>
                </thead>
                <!-- <tr ng-repeat="list in users | orderBy: 'complete_name'"> -->
                <tr ng-repeat="list in inventoryList">
                    <td width="10%">
                        <div class="p-t-5" ng-style="{width : '80px'}">
                            <span>
                                <ul class="actions" data-ng-if="!list.$edit">
                                    <li>
                                        <!-- <a title="Edit" data-ng-click="onEditSpecific(list);"> -->
                                        <a ng-if="userRole.access.edit" title="Edit" data-ng-click="editInventoryForm(list);">
                                            <i class="zmdi zmdi-edit"></i>
                                        </a>
                                        <a ng-if="userRole.access.delete" title="Delete" data-ng-click="onDeleteInventory(list.key)">
                                            <i class="zmdi zmdi-delete"></i>
                                        </a>
                                    </li>
                                </ul>
                            </span>
                        </div>
                    </td>

                    <td>
                        <div class="p-t-2" ng-style="{width:'100%'}">
                            <b>{{ list.item_name }}</b> <br>
                            <span style="color:gray">{{ list.item_desc }} </span>
                        </div>
                    </td>
                    <td>
                        {{ list.brand_name }} 
                    </td>
                    <td>
                        {{ list.category_name }} 
                    </td>
                    <td>
                        {{ list.price }} 
                    </td>
                    <td>
                        {{ list.qty }} 
                    </td>
                    <td>
                        <div class="p-t-2" ng-style="{width:'100%'}">
                            <i class="zmdi zmdi-account"></i> {{ list.created_by }} <br>
                            <i class="zmdi zmdi-calendar"></i> {{ list.created_at }}
                        </div>
                    </td>
                </tr>
                <tr ng-if="inventoryList.length == 0">
                    <td colspan="7" ><center>No record(s) found</center></td>
                </tr>
            </table>
        </div>
    </div>

    <!-- Add User Form -->
    <script type="text/ng-template" id="addInventoryForm">
        <div class="modal-header p-b-15">
            <i class="close zmdi zmdi-close zmdi-hc-fw" ng-click="clearFields();cancel();"></i>
            <h2 class="text-center">ADD NEW ITEM</h2>
        </div>
        <div class="modal-body p-b-0 " style="padding:0 25% 0; height:auto;">
            <div class="row p-l-25" style="width:100%">
                <div class="form-group p-l-15" style="width:100%">
                    All fields with <span class="c-red">*</span> are required
                </div>
                <div class="col-sm-12 m-b-10">
                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line">
                                <label style="z-index:1024;">Item Name
                                    <span class="c-red">*</span>
                                </label>
                                 <input id="unit_name" class="form-control bgm-white p-l-5" type="text" ng-model="inventory.item_name" maxlength="50" placeholder="Item Name"
                                 />
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line">
                                <label style="z-index:1024;">Barcode
                                    <span class="c-red">*</span>
                                </label>
                                 <input id="unit_name" class="form-control bgm-white p-l-5" type="text" ng-model="inventory.barcode" maxlength="50" placeholder="Barcode"
                                 />
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12 m-b-10">


                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line" >
                                <label style="z-index:1024;">Category
                                    <span class="c-red">*</span>
                                </label>
                                <select class="form-control" ng-model="inventory.category"  >
                                <option disabled>SELECT CATEGORY</option>

                                    <option ng-repeat="d in category_list" value="{{ d.key }}">{{ d.category_name }}</option>
                                </select>
                                 
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line" >
                                <label style="z-index:1024;">Unit
                                    <span class="c-red">*</span>
                                </label>
                                <select class="form-control" ng-model="inventory.unit">
                                <option disabled>SELECT UNIT</option>

                                    <option ng-repeat="d in unit_list" value="{{ d.key }}">{{ d.unit_name }}</option>
                                </select>
                                 
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12 m-b-10">


                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line" >
                                <label style="z-index:1024;">Brand
                                    <span class="c-red">*</span>
                                </label>
                                <select class="form-control" ng-model="inventory.brand">
                                    <option disabled>SELECT BRAND</option>
                                    <option ng-repeat="d in brand_list" value="{{ d.key }}">{{ d.brand_name }}</option>
                                </select>
                                
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line">
                                <label style="z-index:1024;">Quantity
                                    <span class="c-red">*</span>
                                </label>
                                 <input id="unit_name" class="form-control bgm-white p-l-5" type="text" ng-model="inventory.qty" maxlength="50" placeholder="Quantity"
                                 />
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12 m-b-10">


                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line" >
                                <label style="z-index:1024;">Price
                                    <span class="c-red">*</span>
                                </label>
                                <input id="unit_name" class="form-control bgm-white p-l-5" type="text" ng-model="inventory.price" maxlength="50" placeholder="Price">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12 m-b-10">
                    <div class="col-sm-12 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line">
                                <label style="z-index:1024;">Item Description
                                    <span class="c-red">*</span>
                                </label>
                                <textarea class="form-control bgm-white p-l-5" ng-model="inventory.item_desc" placeholder="Item Description..." style="height:100px;"></textarea>
                    
                            </div>
                        </div>
                    </div>

                </div>
            </div>
              <div class="p-l-25 row">
                <div class="col-sm-12 m-b-10 p-5">
                    <button type="button" style="width: 98%;" class="btn btn-primary btn-block p-t-10 p-b-10" ng-click="addNewItem();">
                        Add Entry
                    </button>
                </div>
             </div>
        </div>
        <div class="modal-footer p-t-0 p-l-25 p-r-30">

        </div>
    </script>

    <script type="text/ng-template" id="editInventoryForm">
        <div class="modal-header p-b-15">
            <i class="close zmdi zmdi-close zmdi-hc-fw" ng-click="clearFields();cancel();"></i>
            <h2 class="text-center">EDIT ITEM</h2>
        </div>
        <div class="modal-body p-b-0 " style="padding:0 25% 0; height:auto;">
            <div class="row p-l-25" style="width:100%">
                <div class="form-group p-l-15" style="width:100%">
                    All fields with <span class="c-red">*</span> are required
                </div>
                <div class="col-sm-12 m-b-10">
                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line">
                                <label style="z-index:1024;">Item Name
                                    <span class="c-red">*</span>
                                </label>
                                 <input id="unit_name" class="form-control bgm-white p-l-5" type="text" ng-model="inventory.edit_item_name" maxlength="50" placeholder="Item Name"
                                 />
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line">
                                <label style="z-index:1024;">Barcode
                                    <span class="c-red">*</span>
                                </label>
                                 <input id="unit_name" class="form-control bgm-white p-l-5" type="text" ng-model="inventory.edit_barcode" maxlength="50" placeholder="Barcode"
                                 />
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12 m-b-10">


                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line" >
                                <label style="z-index:1024;">Category
                                    <span class="c-red">*</span>
                                </label>
                                <select class="form-control" ng-model="inventory.edit_category"  >
                                <option disabled>SELECT CATEGORY</option>

                                    <option ng-repeat="d in category_list" value="{{ d.key }}">{{ d.category_name }}</option>
                                </select>
                                 
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line" >
                                <label style="z-index:1024;">Unit
                                    <span class="c-red">*</span>
                                </label>
                                <select class="form-control" ng-model="inventory.edit_unit">
                                <option disabled>SELECT UNIT</option>

                                    <option ng-repeat="d in unit_list" value="{{ d.key }}">{{ d.unit_name }}</option>
                                </select>
                                 
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12 m-b-10">


                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line" >
                                <label style="z-index:1024;">Brand
                                    <span class="c-red">*</span>
                                </label>
                                <select class="form-control" ng-model="inventory.edit_brand">
                                    <option disabled>SELECT BRAND</option>
                                    <option ng-repeat="d in brand_list" value="{{ d.key }}">{{ d.brand_name }}</option>
                                </select>
                                
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line">
                                <label style="z-index:1024;">Quantity
                                    <span class="c-red">*</span>
                                </label>
                                 <input id="unit_name" class="form-control bgm-white p-l-5" type="text" ng-model="inventory.edit_qty" maxlength="50" placeholder="Quantity"
                                 />
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12 m-b-10">


                    <div class="col-sm-6 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line" >
                                <label style="z-index:1024;">Price
                                    <span class="c-red">*</span>
                                </label>
                                <input id="unit_name" class="form-control bgm-white p-l-5" type="text" ng-model="inventory.edit_price" maxlength="50" placeholder="Price">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12 m-b-10">
                    <div class="col-sm-12 m-b-10">
                        <div class="form-group m-b-5">
                            <div id="completeNameContainer" class="fg-line">
                                <label style="z-index:1024;">Item Description
                                    <span class="c-red">*</span>
                                </label>
                                <textarea class="form-control bgm-white p-l-5" ng-model="inventory.edit_item_desc" placeholder="Item Description..." style="height:100px;"></textarea>
                    
                            </div>
                        </div>
                    </div>

                </div>
            </div>
              <div class="p-l-25 row">
                <div class="col-sm-12 m-b-10 p-5">
                    <button type="button" style="width: 98%;" class="btn btn-primary btn-block p-t-10 p-b-10" ng-click="updateInventory();">
                        Add Entry
                    </button>
                </div>
             </div>
        </div>
        <div class="modal-footer p-t-0 p-l-25 p-r-30">

        </div>
    </script>

</div>
