<?php
    $session  =   $this->session->get('auth-psslai');
    $baseurl = $this->baseurl;
?>
<!DOCTYPE html>
    <!--[if IE 9 ]><html class="ie9" data-ng-app="streakUX" data-ng-controller="streakUXCtrl as uxctrl" data-useragent=""><![endif]-->
    <![if IE 9 ]><html data-ng-app="psslai" data-ng-controller="streakUXCtrl as uxctrl" data-useragent=""><![endif]>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title update-title></title>

        <!-- Vendor CSS -->
        <link href="vendors/bower_components/animate.css/animate.min.css" rel="stylesheet"> 
        <link href="vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css" rel="stylesheet">
        <link href="vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.css" rel="stylesheet">
        <link href="vendors/bower_components/angular-loading-bar/src/loading-bar.css" rel="stylesheet">
        <link href="vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet">

        <!-- CSS -->
        <link href="css/app.min.1.css" rel="stylesheet" id="app-level">
        <link href="css/app.min.2.css" rel="stylesheet">
        <link href="css/style.css" rel="stylesheet">
        <?php if(count($session) == 0){?>
            <script type="">window.localStorage.clear();</script>
        <?php }?>
    </head>

    <body data-ng-class="{ 'sw-toggled': uxctrl.layoutType === '1'}" style="overflow: auto !important;">
        <?php echo $this->getContent();  ?>
        <data ui-view class="content-page">
            <div class="dim"></div>
        </data>
        <!-- Older IE warning message -->
        <!--[if lt IE 9]>
            <div class="ie-warning">
                <h1 class="c-white">Warning!!</h1>
                <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>
                <div class="iew-container">
                    <ul class="iew-download">
                        <li>
                            <a href="http://www.google.com/chrome/">
                                <img src="img/browsers/chrome.png" alt="">
                                <div>Chrome</div>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.mozilla.org/en-US/firefox/new/">
                                <img src="img/browsers/firefox.png" alt="">
                                <div>Firefox</div>
                            </a>
                        </li>
                        <li>
                            <a href="http://www.opera.com">
                                <img src="img/browsers/opera.png" alt="">
                                <div>Opera</div>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.apple.com/safari/">
                                <img src="img/browsers/safari.png" alt="">
                                <div>Safari</div>
                            </a>
                        </li>
                        <li>
                            <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                                <img src="img/browsers/ie.png" alt="">
                                <div>IE (New)</div>
                            </a>
                        </li>
                    </ul>
                </div>
                <p>Sorry for the inconvenience!</p>
            </div>
        <![endif]-->
        <!-- Core -->
        <script src="vendors/bower_components/jquery/dist/jquery.min.js"></script>

        <!-- Angular -->
        <script src="vendors/bower_components/angular/angular.min.js"></script>
        <script src="vendors/bower_components/angular-animate/angular-animate.min.js"></script>
        <script src="vendors/bower_components/angular-resource/angular-resource.min.js"></script>

        <!-- Angular Modules -->
        <script src="vendors/bower_components/angular-ui-router/release/angular-ui-router.min.js"></script>
        <script src="vendors/bower_components/angular-loading-bar/src/loading-bar.js"></script>
        <script src="vendors/bower_components/oclazyload/dist/ocLazyLoad.min.js"></script>
        <script src="vendors/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>

        <!-- Common Vendors -->
        <script src="vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
        <script src="vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.min.js"></script>
        <script src="vendors/bower_components/Waves/dist/waves.min.js"></script>
        <script src="vendors/bootstrap-growl/bootstrap-growl.min.js"></script>
        <script src="vendors/bower_components/ng-table/dist/ng-table.js"  defer="defer"></script>

        <!-- Excel Parser -->
        <script src="vendors/excel-parser/src/Blob.js"></script>
        <script src="vendors/excel-parser/src/FileSaver.js"></script>
        <script src="vendors/excel-parser/src/jszip.js"></script>
        <script src="vendors/excel-parser/src/xlsx.full.min.js"></script>
        <script src="vendors/excel-parser/src/xlsx.js"></script>

        <!-- Input Mask -->
        <script type="text/javascript" src="vendors/input-mask/input-mask.min.js" ></script>
        <script type="text/javascript" src="vendors/input-mask/jquery-input-mask.js" ></script>

        <!-- Placeholder for IE9 -->
        <!--[if IE 9 ]>
            <script src="vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js"></script>
        <![endif]-->
        <script src="vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js"></script>
        <!-- Using below vendors in order to avoid misloading on resolve -->
        <script src="vendors/bower_components/flot/jquery.flot.js"></script>
        <script src="vendors/bower_components/flot.curvedlines/curvedLines.js"></script>
        <script src="vendors/bower_components/flot/jquery.flot.resize.js"></script>
        <script src="vendors/bower_components/moment/min/moment.min.js"></script>
        <script src="vendors/bower_components/fullcalendar/dist/fullcalendar.min.js"></script>
        <script src="vendors/bower_components/flot-orderBars/js/jquery.flot.orderBars.js"></script>
        <script src="vendors/bower_components/flot/jquery.flot.pie.js"></script>
        <script src="vendors/bower_components/flot.tooltip/js/jquery.flot.tooltip.min.js"></script>
        <script src="vendors/bower_components/angular-nouislider/src/nouislider.min.js"></script>


        <!-- App level -->
        <script>
            var baseUrl =   "<?php echo $baseurl;?>",
                key     =   '',
                page    =   1,
                row     =   10,
                type    =   "DESC",
                sortVal =   "id",
                isLogged=   '<?php echo count($session) != 0 ? true : false; ?>';
            var doc = document.documentElement;
                doc.setAttribute('data-useragent', navigator.userAgent);
        </script>
        <script src="js/ie.support.js"></script>
        <script src="js/app.js"></script>
        <script src="js/services.js"></script>
        <script src="js/config.js"></script>
        <script src="js/filter.js"></script>
        <script src="js/controllers/main.js"></script>
        <script src="js/controllers/users.js"></script>
        <script src="js/controllers/settings.js"></script>
        <script src="js/controllers/inventory.js"></script>
        <script src="js/controllers/transactions.js"></script>


        <script src="<?php echo $baseurl;?>/js/angular-validator.min.js"></script>
        <script src="js/directives.js"></script>
        <script src="<?php echo $baseurl;?>/js/cacheTemplate.js"></script>
    </body>
</html>
